#!/usr/bin/env node
/**
 * Scrape the complete letter listing from bahai.org and generate letterIndex.ts
 */
import puppeteer from 'puppeteer';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();
await page.setRequestInterception(true);
page.on('request', req => {
  if (['image', 'stylesheet', 'font', 'media'].includes(req.resourceType())) req.abort();
  else req.continue();
});

console.log('Loading messages listing page...');
await page.goto('https://www.bahai.org/library/authoritative-texts/the-universal-house-of-justice/messages/', {
  waitUntil: 'networkidle2',
  timeout: 60000,
});
await new Promise(r => setTimeout(r, 5000));

// Extract structured letter data
const letters = await page.evaluate(() => {
  // Each letter entry in the listing has 3 links with the same href: date, recipient, description
  const allLinks = document.querySelectorAll('a');
  const urlMap = new Map();

  for (const link of allLinks) {
    const match = link.href.match(/messages\/(\d{8}_\d{3})\/1$/);
    if (!match) continue;
    const urlCode = match[1];
    if (!urlMap.has(urlCode)) urlMap.set(urlCode, []);
    urlMap.get(urlCode).push(link.textContent.trim());
  }

  const results = [];
  for (const [urlCode, texts] of urlMap) {
    // texts[0] = date display, texts[1] = recipient, texts[2] = description/title
    results.push({
      urlCode,
      dateText: texts[0] || '',
      recipient: texts[1] || '',
      title: texts[2] || texts[1] || '',
    });
  }
  return results;
});

await browser.close();

console.log(`Found ${letters.length} letters on bahai.org\n`);

// Convert to letterIndex format
const entries = letters.map(l => {
  // Parse date from urlCode (YYYYMMDD)
  const y = l.urlCode.substring(0, 4);
  const m = l.urlCode.substring(4, 6);
  const d = l.urlCode.substring(6, 8);
  const date = `${y}-${m}-${d}`;

  // Generate ID
  const id = `uhj-${l.urlCode.split('_')[0]}`;

  return {
    id,
    title: l.title,
    date,
    recipient: l.recipient,
    urlCode: l.urlCode,
  };
});

// Generate TypeScript source
let ts = `// Index of all UHJ letters — auto-generated from bahai.org
// Full content is in letterContent.json (generated by scripts/fetch-letters.mjs)
export interface LetterEntry {
  id: string;
  title: string;
  date: string;
  recipient: string;
  urlCode: string;
}

export const letterIndex: LetterEntry[] = [\n`;

for (const e of entries) {
  const title = e.title.replace(/'/g, "\\'");
  const recipient = e.recipient.replace(/'/g, "\\'");
  ts += `  { id: '${e.id}', title: '${title}', date: '${e.date}', recipient: '${recipient}', urlCode: '${e.urlCode}' },\n`;
}

ts += `];\n`;

const outPath = join(__dirname, '..', 'src', 'data', 'letterIndex.ts');
writeFileSync(outPath, ts);
console.log(`Wrote ${entries.length} entries to ${outPath}`);

// Also output the raw data for reference
const jsonPath = join(__dirname, 'letter-urls.json');
writeFileSync(jsonPath, JSON.stringify(entries, null, 2));
console.log(`Wrote raw data to ${jsonPath}`);
